version: "3.8"

services:
    laravel:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: lms-api
        depends_on:
            - mysql
        volumes:
            - .:/var/www
        networks:
            - laravel_network

    nginx:
        image: nginx:latest
        container_name: lms_be_nginx
        ports:
            - "${APP_PORT:-9000}:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - laravel
        networks:
            - laravel_network

    mysql:
        image: mysql:8.0
        container_name: lms_mysql
        restart: unless-stopped
        ports:
            - "${DB_DOCKER_PORT:-6789}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-LMSpassword123@}
            MYSQL_DATABASE: ${DB_DATABASE:-lms_db}
            MYSQL_USER: ${DB_USERNAME:-user}
            MYSQL_PASSWORD: ${DB_PASSWORD:-LMSpassword123@}
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel_network

networks:
    laravel_network:

volumes:
    mysql_data:
