version: "3.8"

services:
    laravel:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - .:/var/www/app
        environment:
            - PHP_FPM_PORT=${PHP_FPM_PORT:-8989}
        expose:
            - ${PHP_FPM_PORT:-8989}

    nginx:
        image: nginx:latest
        ports:
            - "${APP_PORT:-9999}:${APP_NGINX_PORT:-89}"
        volumes:
            - .:/var/www/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - laravel

    mysql:
        image: mysql:8.0.30
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-DbPass123@}
            MYSQL_DATABASE: ${DB_DATABASE:-lms-db}
            MYSQL_USER: ${DB_USERNAME:-user}
            MYSQL_PASSWORD: ${DB_PASSWORD:-LMSpassword123@}
        ports:
            - "${DB_PORT_ACCESS:-6789}:${DB_PORT:-3306}"
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
